jobs:
- template: script/azure-pipelines-template-mac.yml
  parameters:
    name: macOS
    vmImage: macOS-10.13

- template: script/azure-pipelines-template-unix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: script/azure-pipelines-template-win.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
